sudo: true
language: node_js
node_js:
  - '11.10'

cache:
  npm: true
  yarn: true
  directories:
    - '$HOME/google-cloud-sdk'

# branches:
#   only:
#     - develop
#     - travis

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_68fd2b2badb8_key -iv $encrypted_68fd2b2badb8_iv -in travis.tar.enc -out travis.tar -d
  - tar xf travis.tar

  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf "$HOME/google-cloud-sdk"; curl https://sdk.cloud.google.com | bash > /dev/null; fi
  - source $HOME/google-cloud-sdk/path.bash.inc

install:
  - yarn
before_script:
  - gcloud auth activate-service-account --key-file=keyfile.json
  - export GOOGLE_APPLICATION_CREDENTIALS=keyfile.json
  - export GCLOUD_ACCOUNT_EMAIL=$(node gcloud.keyfile.js ./keyfile.json client_email)
  - export CLOUDSDK_CORE_PROJECT=$(node gcloud.keyfile.js ./keyfile.json project_id)

script:
  - yarn build

deploy:
  - provider: gae
    keyfile: './keyfile.json'
    project: seraphic-plexus-248012
    no_promote: true
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: yarn deploy:cron
    on:
      branch: master

after_deploy:
  - export APP_VERSION=$(gcloud app versions list --service=default --sort-by=LAST_DEPLOYED --format="table(version.id)" --account=$GCLOUD_ACCOUNT_EMAIL | tail -1)
  - gcloud app services set-traffic default --splits $APP_VERSION=1 --migrate --account=$GCLOUD_ACCOUNT_EMAIL
  - curl seraphic-plexus-248012.appspot.com
