runtime: nodejs10
env_variables:
  NODE_ENV: production

instance_class: B1
basic_scaling:
  max_instances: 1
inbound_services:
  - warmup

service: default
handlers:
  - url: /.*
    secure: always
    script: auto
