name: github-actions/docker/build-and-push
on:
  pull_request:
    branches:
      - main
    types: [labeled, synchronize, opened]

  push:
    branches:
      - main

env:
  REGISTRY: ${{ secrets.HARBOR_URL }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'deploy') || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    name: Docker build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node-14-${{ hashFiles('yarn.lock') }}

      - name: Install packages
        run: yarn

      - name: Build
        run: yarn build

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: .next
          path: .next

  push:
    if: contains(github.event.pull_request.labels.*.name, 'deploy') || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    name: Docker push
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node-14-production-${{ hashFiles('yarn.lock') }}

      - name: Install packages
        run: yarn --production
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: .next
          path: .next

      - name: Set docker registry (PR)
        run: echo "DOCKER_REGISTRY=$REGISTRY/pr" >> $GITHUB_ENV
        if: contains(github.event.pull_request.labels.*.name, 'deploy')

      - name: Set docker registry (deployment)
        run: echo "DOCKER_REGISTRY=$REGISTRY/develop" >> $GITHUB_ENV
        if: "!contains(github.event.pull_request.labels.*.name, 'deploy')"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Short sha
        id: sha
        run: echo "::set-output name=sha_short::$(echo ${GITHUB_HEAD_SHA:0:7})"
        env:
          GITHUB_HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=raw,value=${{ steps.sha.outputs.sha_short }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.HARBOR_USER_ID }}
          password: ${{ secrets.HARBOR_USER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: ${{ contains(github.event.pull_request.labels.*.name, 'deploy') || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
